spring.profiles.default: local

---

spring.config.activate.on-profile: local

---

#spring.config.activate.on-profile: prod

---

spring:
  config:
    import:
      - classpath:/application-oauth.yml
      - classpath:/application-tour.yml